name: OpenTofu

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: tofu fmt
        run: tofu fmt -check -recursive -diff

      - name: tofu init
        run: tofu init -backend=false

      - name: tofu validate
        run: tofu validate

      - name: tofu validate (modules/vm)
        run: |
          cd modules/vm
          tofu init -backend=false
          tofu validate

      - name: tofu validate (modules/lxc)
        run: |
          cd modules/lxc
          tofu init -backend=false
          tofu validate
